# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1392121047);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1392121392);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1392119900);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1392120753);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 9);
user_pref("browser.pagethumbnails.storage_version", 2);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.buildID", "20130417085609");
user_pref("browser.startup.homepage_override.mstone", "20.0");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1392206294488");
user_pref("datareporting.policy.firstRunTime", "1392119894488");
user_pref("datareporting.sessions.current.activeTicks", 12);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 719);
user_pref("datareporting.sessions.current.main", 34);
user_pref("datareporting.sessions.current.sessionRestored", 779);
user_pref("datareporting.sessions.current.startTime", "1392122110115");
user_pref("datareporting.sessions.current.totalTime", 72397);
user_pref("datareporting.sessions.currentIndex", 7);
user_pref("datareporting.sessions.previous.0", "{\"s\":1392119882385,\"a\":1,\"t\":34430,\"c\":false,\"m\":1515,\"fp\":19411,\"sr\":23726}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1392120632335,\"a\":31,\"t\":206293,\"c\":true,\"m\":57,\"fp\":1404,\"sr\":1633}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1392120913962,\"a\":2,\"t\":9374,\"c\":true,\"m\":47,\"fp\":787,\"sr\":892}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1392120926587,\"a\":10,\"t\":197728,\"c\":true,\"m\":37,\"fp\":643,\"sr\":725}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1392121207379,\"a\":9,\"t\":61041,\"c\":true,\"m\":16,\"fp\":786,\"sr\":862}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1392121271163,\"a\":27,\"t\":573653,\"c\":true,\"m\":48,\"fp\":812,\"sr\":879}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1392121880884,\"a\":11,\"t\":224228,\"c\":true,\"m\":32,\"fp\":731,\"sr\":797}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.w3c_touch_events.expose", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"webapps-team@lists.launchpad.net\":{\"version\":\"2.4.6\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\"}}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "globalmenu%40ubuntu.com:4.0,%7B2e1445b0-2682-11e1-bfc2-0800200c9a66%7D:2013.04.05.beta,ubufox%40ubuntu.com:2.6,online-accounts%40lists.launchpad.net:0.4.5,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:20.0");
user_pref("extensions.hotfix.certs.1.sha1Fingerprint", "91:53:98:0C:C1:86:DF:47:8F:35:22:9E:11:C9:A7:31:04:49:A1:AA");
user_pref("extensions.hotfix.lastVersion", "20130826.01");
user_pref("extensions.installCache", "[{\"name\":\"app-system-local\",\"addons\":{\"online-accounts@lists.launchpad.net\":{\"descriptor\":\"/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/online-accounts@lists.launchpad.net\",\"mtime\":1366823072000}}},{\"name\":\"app-system-share\",\"addons\":{\"{2e1445b0-2682-11e1-bfc2-0800200c9a66}\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{2e1445b0-2682-11e1-bfc2-0800200c9a66}\",\"mtime\":1366823071000},\"webapps-team@lists.launchpad.net\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"mtime\":1366823072000},\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1366823071000}}},{\"name\":\"app-global\",\"addons\":{\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1386344469000},\"globalmenu@ubuntu.com\":{\"descriptor\":\"/usr/lib/firefox/extensions/globalmenu@ubuntu.com\",\"mtime\":1366823032000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1366823032000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1386344469000}}}]");
user_pref("extensions.lastAppVersion", "20.0");
user_pref("extensions.lastPlatformVersion", "20.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20130417085609");
user_pref("gecko.mstone", "20.0");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.protocol-handler.app.luhyavm", "/storage/bin/luhyavm-linux-handler.py");
user_pref("network.protocol-handler.expose.luhyavm", false);
user_pref("network.protocol-handler.external.luhyavm", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 103668);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1392122110);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1394712751);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
