#! /bin/bash

function desc_step() {
    echo "#######################################################"
    echo "#### $1"
    echo "#######################################################"
}

SRC_ROOT=/mnt/src/eduCloud

#1 prepare directory
desc_step "1. prepare directory"

test -d "/var/log/educloud" || sudo mkdir /var/log/educloud

test -d "/storage" || sudo mkdir /storage/
cd /storage
test -d "images"   || sudo mkdir images VMs config space
cd /storage/space
test -d "software" || sudo mkdir software pub-data prv-data database
cd database
test -d "images"   || sudo mkdir images vms

sudo chown -R luhya:luhya /storage
sudo chown -R luhya:luhya /var/log/educloud
cp $SRC_ROOT/debian/clc.conf /storage/config/
cp $SRC_ROOT/debian/cc.conf  /storage/config/
sudo cp $SRC_ROOT/debian/sudoers  /etc/

test -d "/etc/educloud/modules/" || sudo mkdir -p /etc/educloud/modules/
sudo touch /etc/educloud/modules/cc

#2 prepare dependented packages
desc_step "2. prepare dependented packages"
sudo apt-get install memcached libmemcached-tools apache2 rabbitmq-server libapache2-mod-wsgi python-dev ifstat sysstat sudo openssh-server python-pip sshfs iperf

#3 configure rabbitmq service
desc_step "3. configure rabbitmq service"
sudo rabbitmqctl add_user luhya luhya
sudo rabbitmqctl set_permissions luhya  ".*" ".*" ".*"
sudo service rabbitmq-server restart

#4 prepare & configure rsync service
desc_step "4. prepare & configure rsync service"
sudo cp $SRC_ROOT/webconfig/rsync/rsync /etc/default/
sudo cp $SRC_ROOT/webconfig/rsync/rsyncd.conf /etc/
sudo dpkg -i $SRC_ROOT/webconfig/piplib/3rd/rsync_3.1.0-2ubuntu0.1_amd64.deb

#5 install dependented python package
desc_step "5 install python packages"
cd $SRC_ROOT/webconfig/piplib/3rd
sudo pip install amqp-1.4.3.tar.gz
sudo pip install Django-1.6.1.tar.gz
sudo pip install linux-metrics-0.1.4.tar.gz
sudo pip install pika-0.9.14.tar.gz
sudo pip install psutil-2.1.1.tar.gz
sudo pip install Pynetinfo-0.2.3.tar.gz
sudo pip install python-iptables-0.4.0.tar.gz
sudo pip install python-memcached-1.53.tar.gz
suod pip install sortedcontainers-0.9.4.tar.gz

#6 add $USER into group of fuse
desc_step "6. test sshfs functioin"
./sshid-install clc
