#! /bin/bash

function desc_step() {
    echo "#######################################################"
    echo "#### $1"
    echo "#######################################################"
}

SRC_ROOT=/mnt/src/eduCloud

desc_step "1 configure dhcp service via dnsmasq"

#1.1 disable network-manager's dnsmasq
sudo cp /etc/NetworkManager/NetworkManager.conf /etc/NetworkManager/NetworkManager.conf.pkg
sudo bash -c "cat /etc/NetworkManager/NetworkManager.conf | sed -e 's/dns=dnsmasq/#dns=dnsmasq/' > /etc/NetworkManager/NetworkManager.conf"
sudo restart network-manager

#1.2 install dnsmasq
sudo apt-get install dnsmasq
sudo bash -c "echo \"conf-file=/etc/dnsmasq.d/dnsmasq.intranet.conf\" >> /etc/dnsmasq.conf"

#1.3 prepare statci DHCP IP assignment
sudo cp $SRC_ROOT/webconfig/dhcp/dhcp-lease-notification /usr/bin/
sudo cp $SRC_ROOT/webconfig/dhcp/dnsmasq.intranet.conf /etc/dnsmasq.d/dnsmasq.intranet.conf
sudo cp $SRC_ROOT/webconfig/dhcp/ethers  /etc/

sudo /etc/init.d/dnsmasq restart

