#! /bin/bash

function desc_step() {
    echo "#######################################################"
    echo "#### $1"
    echo "#######################################################"
}

SRC_ROOT=/mnt/src/eduCloud
#1 prepare directory
desc_step "1. prepare directory"
test -d "/var/log/educloud" || sudo mkdir /var/log/educloud

test -d "/storage" || sudo mkdir /storage/
cd /storage
test -d "images"   || sudo mkdir images VMs config space tmp
cd /storage/tmp
test -d "images"   || sudo mkdir images VMs

#### sshfs to mount cc's space to nc's space

sudo chown -R luhya:luhya /storage
sudo chown -R luhya:luhya /var/log/educloud
cp $SRC_ROOT/debian/clc.conf /storage/config/
cp $SRC_ROOT/debian/cc.conf  /storage/config/
sudo cp $SRC_ROOT/debian/sudoers  /etc/

test -d "/etc/educloud/modules/" || sudo mkdir -p /etc/educloud/modules/
sudo touch /etc/educloud/modules/nc

#2 prepare dependented packages
desc_step "2. prepare dependented packages"
sudo apt-get install python-dev ifstat sysstat sudo openssh-server python-pip sshfs iperf

#3 prepare & configure rsync service
desc_step "3. prepare & configure rsync service"
sudo dpkg -i $SRC_ROOT/webconfig/piplib/3rd/rsync_3.1.0-2ubuntu0.1_amd64.deb

#5 install dependented python package
desc_step "4 install python packages"
cd $SRC_ROOT/webconfig/piplib/3rd
sudo pip install linux-metrics-0.1.4.tar.gz
sudo pip install pika-0.9.14.tar.gz
sudo pip install psutil-2.1.1.tar.gz
sudo pip install Pynetinfo-0.2.3.tar.gz
sudo pip install python-iptables-0.4.0.tar.gz
sudo pip install sortedcontainers-0.9.4.tar.gz

#6 add $USER into group of fuse
desc_step "6. test sshfs functioin"
./sshid-install cc
